#!/bin/bash
#
# check if the strtok function was used by using ltrace

command="/bin/ls
/bin/ls
/bin/ls"

# clean up
stop_shell
rm -f $tmp_file

# send commands
echo "$command" | $LTRACE -bc -o $LTRACEOUTPUTFILE $SHELL > $OUTPUTFILE 2> /dev/null &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat $LTRACEOUTPUTFILE | grep strtok | wc -l`
if [ $nmatch -eq 1 ]; then
    print_unhappy
else
    print_happy
fi

# clean up
stop_shell
rm -f $tmp_file
