#!/bin/bash
#
# checks the exit builtin

command="exit"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file
# send commands
echo "$command" | $SHELL 2> $OUTPUTFILE

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat $OUTPUTFILE | wc -c`
if [ $nmatch -eq 0 ]; then
	   print_happy
else
	   print_unhappy
fi

# clean up
stop_shell
rm -f $tmp_file
