#!/bin/bash
#
# check that PATH containing a trailing : is correctly checked

command="ls"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file
# reset PATH
OLDPATH="$PATH"
PATH="/fakedir1:/fakedir2/fakedir3/:"
# send commands
$ECHO "$command" | $SHELL > $OUTPUTFILE 2> $ERROROUTPUTFILE &

# put PATH back
PATH="$OLDPATH"

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
res=`$CAT "$OUTPUTFILE"`
if [ "$res" == "cisfun" ]; then
    print_happy
else
    print_unhappy
fi

# clean up
stop_shell
$RM -f $tmp_file
