#!/bin/bash
#
# test builtin setenv 

command="setenv BETTY holberton
env"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file
# send commands
echo "$command" | $SHELL > $OUTPUTFILE 2> /dev/null &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat $OUTPUTFILE | grep -c "BETTY=holberton"`
if [ $nmatch -eq 1 ]; then
	   print_happy
else
	   print_unhappy
fi

# clean up
stop_shell
rm -f $tmp_file
